### ISSUE TITLE
Not compatible with the built in classic editor

### ISSUE THREAD

**Issue by Youneshimmi99** [shibbirweb/ckeditor5-image-remove-event-callback-plugin#5]
import ImageRemoveEventCallbackPlugin from 'ckeditor5-image-remove-event-callback-plugin'; 
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
throws this error : 
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

**Comment by Youneshimmi99** [comment]
you can import ImageRemoveEventClass (ckeditor5-image-remove-event-callback-plugin\src\ImageRemoveEvent.js) 
instead of:
import ImageRemoveEventCallbackPlugin from 'ckeditor5-image-remove-event-callback-plugin';
but you will have to make some modifications :
remove    :     const { callback } = this.configuration 
change :      return callback(removedImagesSrc, removedImageNodes) To return console.log('callback called', removedImagesSrc, removedImageNodes) (or whatever command you need to do)
and use the ImageRemoveEventClass outside ckeditor you can call it whenever a change has been applied to the editor instead of including the plugin

**Comment by shibbirweb** [comment]
@Youneshimmi99  checkout latest version. Added imageBlock type and set a new configuration to add additional type. 
Also, add a demo project to see the actual implementation of this plugin
