### ISSUE TITLE
imageBlock doesn't trigger the remove event

### ISSUE THREAD

**Issue by Youneshimmi99** [shibbirweb/ckeditor5-image-remove-event-callback-plugin#8]
You need to add change.name === 'imageBlock'
To:  
-- if (change && change.type === 'remove' && (change.name === 'image' || change.name === 'imageInline' || change.name === 'imageBlock')) 

--         const removedNodes = changes.filter(change => (change.type === 'insert' && (change.name === 'image' || change.name === 'imageInline' || change.name === 'imageBlock')))

**Comment by shibbirweb** [comment]
@Youneshimmi99  maybe you should not be trying the latest version of this plugin. In the latest version 'imageBlock' is included.
There is also a demo project in this git repository with 'imageBlock'.
